friends_app/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get '/inicio', to: 'welcome#index'
  get 'welcome/informations'   #, to: 'welcome#show'
  get 'info', to:'welcome#informations'
  get 'info/:name', to:'welcome#informations'

  resources :friends # cria 8 rodas diferentes
  get '/amigos', to: 'friends#index'

  # get '/friends', to: 'friends#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
end

friends_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

friends_app/app/models/friend.rb
class Friend < ApplicationRecord
  validates :name, presence: true
  validates :last_name, presence: true

  # before_save do |friend|
  #   friend.full_name = "#{friend.name} #{friend.last_name}"
  # end

  before_save :update_name

  def update_name
    self.full_name = "#{self.name} #{self.last_name}"
  end
end

friends_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

friends_app/app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
    render layout: "admin"
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:name, :age, :birthday, :last_name)
    end
end

friends_app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  COMPANY = 'Inteligov'
  COURSE = 'Ruby on Rails, first steps'

  def index
  end

  def informations
    @info = "#{COMPANY} - #{COURSE} - #{params[:name]} -  Versão: #{params[:version]}"
  end
end

friends_app/app/helpers/application_helper.rb
module ApplicationHelper
end

friends_app/app/helpers/friends_helper.rb
module FriendsHelper
  def full_info(friend)
    "Hey, friend! #{friend.name}"
  end
end

friends_app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

friends_app/app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :birthday, style: "display: block" %>
    <%= form.date_field :birthday %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

friends_app/app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">

  <%= full_info(friend) %>

  <p>
    <strong>Name:</strong>
    <%= friend.name %>
  </p>

  <p>
    <strong>Last Name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= friend.age %>
  </p>

  <p>
    <strong>Birthday:</strong>
    <%= friend.birthday %>
  </p>

</div>

friends_app/app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend %> |
  <%= link_to "Back to friends", friends_path %>
</div>

friends_app/app/views/friends/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Friends</h1>

<div id="friends">
  <% @friends.each do |friend| %>
    <%= render friend %>
    <p>
      <%= link_to "Show this friend", friend %>
    </p>
  <% end %>
</div>

<%= link_to "New friend", new_friend_path %>

friends_app/app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path %>
</div>

friends_app/app/views/friends/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @friend %>

<div>
  <%= link_to "Edit this friend", edit_friend_path(@friend) %> |
  <%= link_to "Back to friends", friends_path %>

  <%= button_to "Destroy this friend", @friend, method: :delete %>
</div>

friends_app/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FriendsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= yield %>

     <h1>ADMIN</h1>
  </body>
</html>

friends_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FriendsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "/shared/menu" %>
    <%= yield %>
  </body>
</html>

friends_app/app/views/shared/_menu.html.erb
<h1>Aqui ficará um menu</h1>

friends_app/app/views/welcome/index.html.erb
<h1>Bem-vindos ao sistema!!</h1>

friends_app/app/views/welcome/informations.html.erb
<h1><%= @info %></h1>